#!/usr/bin/env python
 
# Made by Soeren Schmidt Kriegbaum - http://hyggeit.blogspot.dk/

# Use Adafruit linux dist as they have allready added Gpio and spi support
# http://learn.adafruit.com/adafruit-raspberry-pi-educational-linux-distro/overview

# Install notes:
#$ sudo apt-get install apache2
#$ sudo apt-get install mysql-server
#$ sudo apt-get install python-mysqldb
#$ sudo apt-get install phpmyadmin
#$ mysql -u root -p
#CREATE DATABASE measurepower
#CREATE USER 'measurepower'@'localhost' IDENTIFIED BY 'yourpasswordhere';
#GRANT ALL ON measurepower.* TO 'measurepower'@'%';

#CREATE TABLE IF NOT EXISTS `watthours` (
#  `id` int(11) NOT NULL AUTO_INCREMENT,
#  `datetime` datetime NOT NULL,
#  `lightvalue` int(11) NOT NULL,
#  PRIMARY KEY (`id`),
#  KEY `id` (`id`)
#) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;

 
import RPi.GPIO as GPIO, time, os      
import MySQLdb as mdb
import sys


def Writewatt (lightvalue):
    con = None
    try:
        con = mdb.connect('localhost', 'measurepower', 'yourpasswordhere', 'measurepower');
        cur = con.cursor()
        cur.execute("INSERT INTO measurepower.watthours (id, datetime, lightvalue) VALUES (NULL, NOW(), '%s')" % lightvalue)
        con.commit()
    except mdb.Error, e:
        print "Error %d: %s" % (e.args[0],e.args[1])
        sys.exit(1)
    finally:        
        if con:    
            con.close()

DEBUG = 1
GPIO.setmode(GPIO.BCM)
 
def RCtime (RCpin):
        reading = 0
        GPIO.setup(RCpin, GPIO.OUT)
        GPIO.output(RCpin, GPIO.LOW)
        GPIO.setwarnings(False)
        time.sleep(0.01)
 
        GPIO.setup(RCpin, GPIO.IN)
        # This takes about 1 millisecond per loop cycle
        while (GPIO.input(RCpin) == GPIO.LOW):
                reading += 1
        return reading


while True:
    if 1==1:
        break
    else:
        pass

 
while True:
    result = RCtime(18)
    if result<=150:
        print 'Light value:'
        print result	     # Read RC timing using pin #18
        Writewatt(result)
        time.sleep(0.1)
